name: Compile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  VERSION: "3.1.2"
  UNDERSCORE_VERSION: "3_1_2"

jobs:
  build:

    runs-on: ${{matrix.os}}

    strategy: 
      matrix:
        include:
          - os: macos-latest
            name: macos_x86_64
            target: x86_64-apple-darwin
       #   - os: macos-latest
       #     name: macos_aarch64
       #     target: aarch64-apple-darwin
          - os: ubuntu-latest
            name: linux_x86_64
            target: x86_64-unknown-linux-gnu
       #   - os: ubuntu-latest
       #     name: linux_aarch64
       #     target: aarch64-unknown-linux-gnu
       #   - os: windows-latest
       #     name: windows_x86_64
       #     target: x86_64-pc-windows-msvc
    steps:
    - name: make download directory
      run: mkdir download
    - uses: suisei-cn/actions-download-file@v1.3.0
      id: downloadfile  # Remember to give an ID if you need the output filename
      name: Download the file
      with:
        url: "https://github.com/ruby/ruby/archive/refs/tags/v${{env.UNDERSCORE_VERSION}}.tar.gz"
        target: download
    - name: compile ruby
      run: |
        cd download
        ls
        tar -xvf ruby-${{env.UNDERSCORE_VERSION}}.tar.gz
        cd ruby-${{env.UNDERSCORE_VERSION}}
        mkdir output
        ./configure --prefix="${{env.PWD}}/output"
        make
        make install
        tar -czvf ruby.tar.gz output
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{env.VERSION}}-${{matrix.name}}"
        prerelease: false
        title: "${{env.VERSION}}-${{matrix.name}}"
        files: |
          download/ruby-${{env.UNDERSCORE_VERSION}}/ruby.tar.gz
