name: Compile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  VERSION: "3.2.2"
  SHORT_VERSION: "3.2"

jobs:
  build:

    runs-on: ${{matrix.os}}

    strategy: 
      matrix:
        include:
          - os: macos-latest
            name: macos_x86_64
            conan_target: default
            target: x86_64-apple-darwini
            arch: x86_64
            build: x86_64-apple-darwin
          - os: macos-latest
            name: macos_aarch64
            conan_target: m1profile
            target: aarch64-apple-darwin
            arch: aarch64
            build: x86_64-apple-darwin
          - os: ubuntu-latest
            name: linux_x86_64
            conan_target: default
            target: x86_64-unknown-linux-gnu
            arch: x86_64
            build: x86_64-unknown-linux-gnu
       #   - os: ubuntu-latest
       #     name: linux_aarch64
       #     target: aarch64-unknown-linux-gnu
       #   - os: windows-latest
       #     name: windows_x86_64
       #     target: x86_64-pc-windows-msvc
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: Download the file
      uses: suisei-cn/actions-download-file@v1.3.0
      id: downloadfile  # Remember to give an ID if you need the output filename
      with:
        url: "https://cache.ruby-lang.org/pub/ruby/${{env.SHORT_VERSION}}/ruby-${{env.VERSION}}.tar.gz"
        target: download
    - name: compile ruby
      run: |
        cd download
        ls
        tar -xvf ruby-${{env.VERSION}}.tar.gz
        mv ruby-${{env.VERSION}} ..
        echo "git workspace: ${{github.workspace}}"
        cd ..
        ./solipath poetry install
        ./solipath poetry run conan profile detect
        ./solipath poetry run conan install --build=missing --profile:host=${{matrix.conan_target}} -of build .
        cd build
        chmod +x conanbuild.sh
        ./conanbuild.sh && ../ruby-${{env.VERSION}}/configure --build=${{matrix.build}} --host=${{matrix.target}} --target=${{matrix.target}} --enable-load-relative --disable-shared --enable-static --without-gmp --prefix="$PWD/bin" && make ARCH=${{matrix.arch}} CROSS_COMPILE=${{matrix.target}} && make install
        tar -czvf ruby.tar.gz bin
    - name: release ruby
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{env.VERSION}}-${{matrix.name}}"
        prerelease: false
        title: "${{env.VERSION}}-${{matrix.name}}"
        files: |
          build/ruby.tar.gz
          
