name: M1 Mac Compile

#Temporary startup and env
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
env:
  CARGO_TERM_COLOR: always
  VERSION: "3.2.2"
  SHORT_VERSION: "3.2"

#The eventual actual startup and env
# on: 
#   workflow_dispatch:
#     inputs:
#       VERSION:
#         required: true
#         type: string
#       SHORT_VERSION:
#         required: true
#         type: string

# env:
#   CARGO_TERM_COLOR: always
#   VERSION: ${{inputs.VERSION}}
#   SHORT_VERSION: ${{inputs.SHORT_VERSION}}

jobs:
  build:

    runs-on: ${{matrix.os}}

    strategy: 
      matrix:
        include:
          - os: macos-latest
            name: macos_aarch64
            target: aarch64-apple-darwin
            compiler: clang -arch arm64
            build: x86_64-apple-darwin

    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: Download openssl
      id: openssl
      uses: suisei-cn/actions-download-file@v1.3.0
      with:
        url: "https://github.com/openssl/openssl/releases/download/OpenSSL_1_1_1w/openssl-1.1.1w.tar.gz"
        target: openssl
    - name: Download the ruby
      uses: suisei-cn/actions-download-file@v1.3.0
      id: downloadfile  # Remember to give an ID if you need the output filename
      with:
        url: "https://cache.ruby-lang.org/pub/ruby/${{env.SHORT_VERSION}}/ruby-${{env.VERSION}}.tar.gz"
        target: download
    - name: configure and build openssl
      run: |
        cd openssl
        ls
        tar -xvf openssl-1.1.1wtar.gz
        cd openssl-1.1.1w
        mkdir build
        cd build
        CC=${{matrix.compiler}} ../Configure --prefix="${{github.workspace}}/libraries" darwin64-arm64-cc no-shared
        make
        make install
    - name: configure ruby build
      run: |
        uname -m
        cd download
        ls
        tar -xvf ruby-${{env.VERSION}}.tar.gz
        mv ruby-${{env.VERSION}} ..
        echo "git workspace: ${{github.workspace}}"
        cd ..
        mkdir build
        cp solipath build
        cd build
        echo '[{"name": "ruby", "version": "${{env.VERSION}}"}]' > solipath.json
        ./solipath CFLAGS="${{github.workspace}}/libraries/lib" ../ruby-${{env.VERSION}}/configure CC='${{matrix.compiler}}' LD='${{matrix.compiler}}' CXX="clang++ -arch arm64" --build=${{matrix.build}} --host=${{matrix.target}} --target=${{matrix.target}} --enable-load-relative --disable-shared --enable-static --without-gmp --prefix="$PWD/bin"
    - name: compile ruby
      run: |
        cd build
        ls -a
        echo "Print Makefile:"
        cat Makefile
        echo "start build"
        #./conanbuild.sh && 
        #CC='${{matrix.compiler}}' LD='${{matrix.compiler}}' && ./solipath make CC='${{matrix.compiler}}' LD='${{matrix.compiler}}' && make install CC='${{matrix.compiler}}' LD='${{matrix.compiler}}'
        MINIRUBY="$BASERUBY" && ./solipath make V=1 CC='${{matrix.compiler}}' LD='${{matrix.compiler}}' CXX="clang++ -arch arm64"
        ls
        head -3 miniruby
        echo "start install"
        MINIRUBY="$BASERUBY" && ./solipath make install CC='${{matrix.compiler}}' LD='${{matrix.compiler}}'
        tar -czvf ruby.tar.gz bin
    - name: release ruby
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{env.VERSION}}-${{matrix.name}}"
        prerelease: false
        title: "${{env.VERSION}}-${{matrix.name}}"
        files: |
          build/ruby.tar.gz
          
